# Generated by Django 4.2.1 on 2023-06-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organiser_Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiser_events',
            name='event_picture',
            field=models.ImageField(upload_to='event_images/'),
        ),
    ]
