# Generated by Django 4.2.1 on 2023-06-07 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_organiser_organiser_id_and_more'),
        ('Organiser_Main', '0002_alter_organiser_events_event_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiser_events',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='User.organiser'),
        ),
    ]
