# Generated by Django 4.2.1 on 2023-06-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organiser_Main', '0005_organiser_events_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organiser_events',
            name='organizer',
        ),
    ]
