# Generated by Django 4.2.1 on 2023-06-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_remove_organiser_user'),
        ('Organiser_Main', '0006_remove_organiser_events_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiser_events',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.organiser'),
        ),
    ]
