# Generated by Django 4.2.1 on 2023-06-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_participant_alter_organiser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiser',
            name='organiser_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='particpant_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
