# Generated by Django 4.2.1 on 2023-06-16 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_remove_organiser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiser',
            name='contact',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AddField(
            model_name='participant',
            name='contact',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
